import {
  ArrowRight,
  ClipboardList,
  Download,
  FileCode2,
  FileText,
  GitBranch,
  HardDrive,
  Link2,
  RadioTower,
  Save,
  SearchCheck,
  Server,
  Shield,
  UserRound,
  WalletCards,
} from "lucide-react";
import type { PortalNodeKind, Template } from "./types";

export const heroVideoUrl =
  "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260328_065045_c44942da-53c6-4804-b734-f9e07fc22e08.mp4";

export const heroPartners = ["Portaldot", "Substrate", "ink!", "Vite", "React Flow", "Local Node"];

export const advancedConfigKeys = new Set([
  "account",
  "metadataPath",
  "wasmPath",
  "eventName",
  "constructorArgs",
  "args",
  "gasLimit",
  "contractAddress",
  "mode",
  "target",
]);

export const browserHelperNodeKinds = new Set<PortalNodeKind>([
  "watchEvents",
  "decodeEvents",
  "exportWorkflow",
  "exportCommands",
  "saveWorkflow",
  "loadWorkflow",
  "generateReport",
]);

export const writeTransactionNodeKinds = new Set<PortalNodeKind>([
  "transferPot",
  "deployContract",
  "callMessage",
]);

export const templates: Template[] = [
  {
    kind: "manageLocalNode",
    group: "Environment",
    label: "Local Node Manager",
    description: "Show safe start, stop, and status commands for the local Portaldot node",
    command: "portaldot_dev --dev --alice",
    config: { action: "status" },
    icon: RadioTower,
  },
  {
    kind: "connectRpc",
    group: "Environment",
    label: "Connect RPC",
    description: "Quickly verify that the websocket RPC endpoint is reachable",
    command: "rpc ping {endpoint}",
    config: { endpoint: "ws://127.0.0.1:9944" },
    icon: Server,
  },
  {
    kind: "checkRuntime",
    group: "Environment",
    label: "Check Runtime",
    description: "Confirm contracts runtime support",
    command: "python scripts/doctor.py --url {endpoint}",
    config: {},
    icon: RadioTower,
  },
  {
    kind: "checkAccount",
    group: "Environment",
    label: "Check Account",
    description: "Signer seed and SS58 account",
    command: "PORTALDOT_SEED={seed}",
    config: { seed: "//Alice", account: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY" },
    icon: UserRound,
  },
  {
    kind: "checkBalance",
    group: "Environment",
    label: "Check Balance",
    description: "Read signer balance from System.Account",
    command: "python scripts/query.py --url {endpoint}",
    config: {},
    icon: WalletCards,
  },
  {
    kind: "exploreMetadata",
    group: "Contract Lifecycle",
    label: "Metadata Explorer",
    description: "Parse constructors, messages, and events from ink! metadata",
    command: "inspect metadata {metadataPath}",
    config: { metadataPath: "contract/target/ink/membership.json" },
    icon: FileCode2,
  },
  {
    kind: "transactionPreview",
    group: "Interaction",
    label: "TransactionPreview",
    description: "Estimate fee or dry-run the selected transaction before submission",
    command: "preview {target}",
    config: { target: "transferPot", value: "1000000000000", recipient: "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty" },
    icon: SearchCheck,
  },
  {
    kind: "dryRunCall",
    group: "Interaction",
    label: "Dry Run Call",
    description: "Dry-run a payable contract message and capture gas evidence",
    command: "python scripts/call.py --url {endpoint} --action {message} --value {value} --dry-run-only",
    config: { message: "join", value: "100000000000000" },
    icon: ClipboardList,
  },
  {
    kind: "stateDiff",
    group: "Interaction",
    label: "State Diff",
    description: "Compare account and contract state before and after a workflow step",
    command: "portalmodeler diff state",
    config: {},
    icon: GitBranch,
  },
  {
    kind: "decodeError",
    group: "Utility",
    label: "Error Decoder",
    description: "Explain the latest failed node and suggest the next fix",
    command: "portalmodeler decode latest-error",
    config: {},
    icon: Shield,
  },
  {
    kind: "transferPot",
    group: "Interaction",
    label: "Transfer POT",
    description: "Submit a small local POT transfer and show fee evidence",
    command: "python scripts/transfer.py --url {endpoint} --amount {value}",
    config: {
      value: "1000000000000",
      recipient: "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
    },
    icon: ArrowRight,
  },
  {
    kind: "buildContract",
    group: "Contract Lifecycle",
    label: "Build Contract",
    command: "cd contract && cargo contract build --release",
    description: "Compile the local ink! contract artifacts",
    config: { contractDir: "contract" },
    icon: HardDrive,
  },
  {
    kind: "loadArtifact",
    group: "Contract Lifecycle",
    label: "Load Artifact",
    description: "Load metadata and Wasm without assuming Membership",
    command: "load artifact {metadataPath} {wasmPath}",
    config: {
      metadataPath: "contract/target/ink/membership.json",
      wasmPath: "contract/target/ink/membership.wasm",
    },
    icon: FileCode2,
  },
  {
    kind: "deployContract",
    group: "Contract Lifecycle",
    label: "Deploy Contract",
    description: "Instantiate contract with constructor, value, and gas checks",
    command: "python scripts/deploy.py --url {endpoint} --fee {fee}",
    config: { constructorName: "new", constructorArgs: "{}", fee: "100000000000000", value: "0" },
    icon: Download,
  },
  {
    kind: "attachContract",
    group: "Contract Lifecycle",
    label: "Attach Contract",
    description: "Attach an existing address to loaded metadata",
    command: "attach contract {contractAddress}",
    config: { contractAddress: "" },
    icon: Link2,
  },
  {
    kind: "verifyContractLive",
    group: "Contract Lifecycle",
    label: "Verify Contract",
    description: "Check that the address exists on the current chain",
    command: "python scripts/call.py --url {endpoint} --action join_fee",
    config: {},
    icon: SearchCheck,
  },
  {
    kind: "readMessage",
    group: "Interaction",
    label: "Read Message",
    description: "Run a read-only contract message",
    command: "python scripts/call.py --url {endpoint} --action {message}",
    config: { message: "is_member", args: "{}" },
    icon: SearchCheck,
  },
  {
    kind: "callMessage",
    group: "Interaction",
    label: "Call Message",
    description: "Submit a state-changing contract message",
    command: "python scripts/call.py --url {endpoint} --action {message} --value {value}",
    config: { message: "join", args: "{}", value: "100000000000000", gasLimit: "" },
    icon: Shield,
  },
  {
    kind: "watchEvents",
    group: "Interaction",
    label: "Watch Events",
    description: "Track contract and system events for this address",
    command: "watch events {eventName}",
    config: { eventName: "MemberJoined" },
    icon: RadioTower,
  },
  {
    kind: "decodeEvents",
    group: "Interaction",
    label: "Decode Events",
    description: "Decode observed contract events from metadata",
    command: "decode events from metadata",
    config: {},
    icon: ClipboardList,
  },
  {
    kind: "exportWorkflow",
    group: "Utility",
    label: "Export Workflow",
    description: "Export nodes, edges, configs, and optional outputs",
    command: "portalmodeler export --format json",
    config: {},
    icon: GitBranch,
  },
  {
    kind: "exportCommands",
    group: "Utility",
    label: "Export Commands",
    description: "Generate runnable CLI commands from the board",
    command: "portalmodeler export --format markdown",
    config: {},
    icon: Download,
  },
  {
    kind: "saveWorkflow",
    group: "Utility",
    label: "Save Workflow",
    description: "Save workflow JSON without private seeds by default",
    command: "portalmodeler save workflow",
    config: {},
    icon: Save,
  },
  {
    kind: "loadWorkflow",
    group: "Utility",
    label: "Load Workflow",
    description: "Load a saved workflow JSON",
    command: "portalmodeler load workflow",
    config: {},
    icon: FileText,
  },
  {
    kind: "generateReport",
    group: "Utility",
    label: "Generate Report",
    description: "Create a workflow run summary for sharing",
    command: "portalmodeler report",
    config: {},
    icon: ClipboardList,
  },
];

export const flowOrder: PortalNodeKind[] = [
  "manageLocalNode",
  "connectRpc",
  "checkRuntime",
  "checkAccount",
  "checkBalance",
  "transactionPreview",
  "transferPot",
  "buildContract",
  "loadArtifact",
  "exploreMetadata",
  "deployContract",
  "attachContract",
  "verifyContractLive",
  "dryRunCall",
  "callMessage",
  "readMessage",
  "watchEvents",
  "decodeEvents",
  "stateDiff",
  "decodeError",
  "exportWorkflow",
  "exportCommands",
  "saveWorkflow",
  "loadWorkflow",
  "generateReport",
];

export type FlowEdgeState = "planned" | "running" | "success" | "error";
export type FlowHandleId = "top" | "right" | "bottom" | "left";

export const portalNodeSize = { width: 220, height: 160 };
export const boardZoom = {
  min: 0.25,
  max: 2.2,
  wheelSpeed: 0.001,
};
export const flowHandleIds: FlowHandleId[] = ["top", "right", "bottom", "left"];
